org: giabaodemo
app: demo
service: taskService

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2
  environment:
    DB_USERNAME: 
    DB_PASSWORD: 
    DB_NAME: 
    DB_HOST: 
    DB_PORT: 11435
    ACCESS_TOKEN_SECRET: 
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
        - sns:Subscribe
        - sns:Receive
      Resource: "*"
  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowCredentials: false

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000

resources:
  Resources:
    TaskSNSTopicDev:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: TaskSNS
        Subscription: []  # Có thể để trống, vì bạn đang dùng SNS trigger ở function bên dưới
      # Thêm policy ở đây:
    TaskSNSTopicPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties:
        Topics:
          - Ref: TaskSNSTopicDev
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal: "*"
              Action: "SNS:Publish"
              Resource: !Ref TaskSNSTopicDev



functions:
  taskEventHandler:
    handler: src/functions/tasEventHandler.handler
    events:
      - sns:
          arn: !Ref TaskSNSTopicDev
          topicName: TaskSNS
  # TASK handlers
  getTasks:
    handler: src/functions/getTasks.getTasks
    events:
      - httpApi:
          path: /tasks
          method: get

  createTask:
    handler: src/functions/createTask.createTask
    events:
      - httpApi:
          path: /tasks
          method: post

  getTaskById:
    handler: src/functions/getTask.getTask
    events:
      - httpApi:
          path: /tasks/test
          method: get

  updateTask:
    handler: src/functions/updateTask.updateTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: put

  deleteTask:
    handler: src/functions/deleteTask.deleteTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: delete

package:
  individually: true
  exclude:
    - node_modules/**
    - .git/**
    - .vscode/**
    - test/**
    - README.md
    - package-lock.json
    - tsconfig.json
    - .serverless/**
    - .webpack/**
    - .env